update all file #3

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -55,11 +55,26 @@ jobs:
           else
             echo "pip is up-to-dateo"
           fi
-          
+
+
+      - name: Restore pip cache
+        uses: actions/cache@v2
+        id: pip-cache
+        if: steps.pip-install.outputs.cache-hit != 'true'
+        with:
+          path: $PIP_CACHE_DIR
+          key: $PIP_CACHE_NAME
+
+      
       - name: Install dependencies
         run: |
           pip install -r requirements.txt
-          
+          if [ $? -ne 0 ]; then
+            echo "Cache restored, but some dependencies failed to install. Installing them all again."
+            rm -rf $PIP_CACHE_DIR
+            pip install -r requirements.txt
+          fi
+    
       - name: Cache dependencies
         id: cache-dependencies
         uses: actions/cache@v2
